import type { GameCode } from './saveCodec'

export type IdLookupKind = 'character' | 'class' | 'item'

type GameIdLookup = Readonly<Record<IdLookupKind, Readonly<Record<number, string>>>>

const ID_LOOKUPS: Readonly<Partial<Record<GameCode, GameIdLookup>>> = {
  "FE6": {
    "character": {
      "0": "None",
      "1": "Roy",
      "2": "Clarine",
      "3": "Fa",
      "4": "Shin",
      "5": "Sue",
      "6": "Dayan",
      "7": "Dayan (NPC)",
      "8": "Barth",
      "9": "Bors",
      "10": "Wendy",
      "11": "Douglas",
      "12": "Douglas (NPC)",
      "13": "Wolt",
      "14": "Dorothy",
      "15": "Klein",
      "16": "Saul",
      "17": "Elen",
      "18": "Yodel",
      "19": "Yodel (NPC)",
      "20": "Chad",
      "21": "Karel",
      "22": "Fir",
      "23": "Rutger",
      "24": "Dieck",
      "25": "Oujay",
      "26": "Garet",
      "27": "Alan",
      "28": "Lance",
      "29": "Percival",
      "30": "Igrene",
      "31": "Marcus",
      "32": "Astol",
      "33": "Ward",
      "34": "Lot",
      "35": "Bartre",
      "36": "Bartre (NPC)",
      "37": "Lugh",
      "38": "Lilina",
      "39": "Hugh",
      "40": "Niime",
      "41": "Niime (NPC)",
      "42": "Rei",
      "43": "Lalam",
      "44": "Yunno",
      "45": "Yunno (NPC)",
      "46": "Thito",
      "47": "Thito (enemy)",
      "48": "Thito (NPC)",
      "49": "Thany",
      "50": "Zeiss",
      "51": "Gale",
      "52": "Elfin",
      "53": "Cass",
      "54": "Sophia",
      "55": "Miledy",
      "56": "Gonzales",
      "57": "Gonzales (NPC)",
      "58": "Noah",
      "59": "Treck",
      "60": "Zealot",
      "61": "Echidna",
      "62": "Echidna (NPC)",
      "63": "Cecilia",
      "64": "Geese",
      "65": "Geese (NPC)",
      "66": "Merlinus",
      "67": "Eliwood",
      "68": "Guinevere",
      "69": "Bandit",
      "70": "Bandit",
      "71": "Bandit",
      "72": "Bandit",
      "73": "Bandit",
      "74": "Damas",
      "75": "Rude",
      "76": "Slater",
      "77": "Erik",
      "78": "Dory",
      "79": "Wagner",
      "80": "Devias",
      "81": "Legylance",
      "82": "Scott",
      "83": "Nord",
      "84": "William",
      "85": "Flaer",
      "86": "Oro",
      "87": "Robarts",
      "88": "Aine",
      "89": "Narshen",
      "90": "Randy",
      "91": "Rose",
      "92": "Maggie",
      "93": "Raeth",
      "94": "Arcard",
      "95": "Martel",
      "96": "Sigune",
      "97": "Roartz",
      "98": "Murdock",
      "99": "Brunya",
      "100": "Zephiel",
      "101": "Idoun (no hood)",
      "102": "Idoun (dragon form)",
      "103": "Yahn",
      "104": "Zinc",
      "105": "Monke",
      "106": "Gel",
      "107": "Brigand",
      "108": "Bern",
      "109": "Bern",
      "110": "Bern",
      "111": "Bern",
      "112": "Bern",
      "113": "Laus",
      "114": "Pirate",
      "115": "Bandit",
      "116": "Thria",
      "117": "Rebel",
      "118": "Bern",
      "119": "Rebel",
      "120": "Officials",
      "121": "Thief",
      "122": "Seihou",
      "123": "Pirate",
      "124": "Almar",
      "125": "Robber",
      "126": "Registrans",
      "127": "Eturia",
      "128": "Bandit",
      "129": "Bandit",
      "130": "Bandit",
      "131": "Bern",
      "132": "Eturian",
      "133": "Isle",
      "134": "Bern",
      "135": "Eturia",
      "136": "Bern",
      "137": "Bandit",
      "138": "Eturia",
      "139": "Bern",
      "140": "Ilia",
      "141": "Bandit",
      "142": "Bern",
      "143": "Eturia",
      "144": "Thief",
      "145": "Bern",
      "146": "Bern",
      "147": "Pirate",
      "148": "Pirate",
      "149": "Ilia",
      "150": "Bern",
      "151": "Ilia",
      "152": "Brigand",
      "153": "Ilia",
      "154": "Fighter",
      "155": "Bandit",
      "156": "Ilia",
      "157": "Citizen",
      "158": "Thief",
      "159": "Bern",
      "160": "Bern",
      "161": "Bern",
      "162": "Thief",
      "163": "Bandit",
      "164": "Citizen",
      "165": "Fighter",
      "166": "Eturia",
      "167": "Sacae",
      "168": "Bern",
      "169": "Djute",
      "170": "Sacae",
      "171": "Sacae",
      "172": "Bern",
      "173": "Eturia",
      "174": "Sacae",
      "175": "Bern",
      "176": "Mamkute",
      "177": "Bern",
      "178": "WarDragon",
      "179": "Bandit",
      "180": "Bandit",
      "181": "Henning",
      "182": "Scollan",
      "183": "Bandit",
      "184": "Grero",
      "185": "Ohtz",
      "186": "Teck",
      "187": "Bern",
      "188": "Bern",
      "189": "Bern",
      "190": "Thoril",
      "191": "Brakul",
      "192": "Kudoka",
      "193": "Marral",
      "194": "Kabul",
      "195": "Chan",
      "196": "Pereth",
      "197": "Bern",
      "198": "Windam",
      "199": "Eturia",
      "200": "Morgan",
      "201": "Rebel",
      "202": "Bern",
      "203": "Bern",
      "204": "Bern",
      "205": "Citizen",
      "206": "Citizen",
      "207": "Hector",
      "208": "Bors",
      "209": "Commander",
      "210": "Commander",
      "211": "Percival's Unit",
      "212": "Bandit",
      "213": "Percival's Unit",
      "214": "Percival's Unit",
      "215": "Percival's Unit",
      "216": "Klein's Unit",
      "217": "Tate's Unit",
      "224": "Bandit",
      "225": "Duelist"
    },
    "class": {
      "0": "Nothing",
      "1": "Roy Lord",
      "2": "Mercenary",
      "3": "Mercenary (F)",
      "4": "Hero",
      "5": "Hero (F)",
      "6": "Swordfighter",
      "7": "Swordfighter (F)",
      "8": "Swordmaster",
      "9": "Swordmaster (F)",
      "10": "Axefighter",
      "11": "Warrior",
      "12": "Armour Knight",
      "13": "Armour Knight (F)",
      "14": "General",
      "15": "General (F)",
      "16": "Archer",
      "17": "Archer (F)",
      "18": "Sniper",
      "19": "Sniper (F)",
      "20": "Priest",
      "21": "Sister",
      "22": "Bishop",
      "23": "Bishop (F)",
      "24": "Mage",
      "25": "Mage (F)",
      "26": "Sage",
      "27": "Sage (F)",
      "28": "Shaman",
      "29": "Shaman (F)",
      "30": "Druid",
      "31": "Druid (F)",
      "32": "Socialknight",
      "33": "Socialknight (F) (messed up palette)",
      "34": "Paladin",
      "35": "Paladin (F) (messed up palette)",
      "36": "Troubadour",
      "37": "Valkyrie",
      "38": "Nomad",
      "39": "Nomad (F)",
      "40": "Nomad Trooper",
      "41": "Nomad Trooper (F)",
      "42": "Pegasus Knight",
      "43": "Falcon Knight",
      "44": "Dragon Knight",
      "45": "Dragon Knight (F)",
      "46": "Dragon Master",
      "47": "Dragon Master (F)",
      "48": "Soldier",
      "49": "Mountain Thief",
      "50": "Pirate",
      "51": "Berserker",
      "52": "Thief",
      "53": "Thief (F)",
      "54": "Bard",
      "55": "Dancer",
      "56": "Mamkute",
      "57": "Mamkute (F)",
      "58": "Fire Dragon",
      "59": "Divine Dragon",
      "60": "Magic Dragon",
      "61": "King",
      "62": "Civilian",
      "63": "Civilian (F)",
      "64": "Child",
      "65": "Child (F)",
      "66": "Storage",
      "67": "Roy Master Lord",
      "68": "Archer on Long Arch",
      "69": "Archer on Iron Arch",
      "70": "Archer on Killer Arch",
      "71": "Long Arch",
      "72": "Iron Arch",
      "73": "Killer Arch",
      "74": "Disarmed Sniper (no standing sprites)",
      "75": "Disarmed Sniper (F) (no standing sprites)"
    },
    "item": {
      "0": "None",
      "1": "Iron Sword",
      "2": "Iron Blade",
      "3": "Steel Sword",
      "4": "Silver Sword",
      "5": "Slim Sword",
      "6": "Poison Sword",
      "7": "Hero Sword",
      "8": "Light Brand",
      "9": "Durandal",
      "10": "Armourslayer",
      "11": "Rapier",
      "12": "Killing Edge",
      "13": "Lancereaver",
      "14": "Wo Dao",
      "15": "Sword of Seals",
      "16": "Iron Lance",
      "17": "Steel Lance",
      "18": "Silver Lance",
      "19": "Slim Lance",
      "20": "Poison Lance",
      "21": "Hero Lance",
      "22": "Javelin",
      "23": "Maltae",
      "24": "Horseslayer",
      "25": "Killer Lance",
      "26": "Axereaver",
      "27": "Iron Axe",
      "28": "Steel Axe",
      "29": "Silver Axe",
      "30": "Poison Axe",
      "31": "Hero Axe",
      "32": "Hand Axe",
      "33": "Armads",
      "34": "Hammer",
      "35": "Killer Axe",
      "36": "Swordreaver",
      "37": "Devil Axe",
      "38": "Halberd",
      "39": "Iron Bow",
      "40": "Steel Bow",
      "41": "Silver Bow",
      "42": "Poison Bow",
      "43": "Killer Bow",
      "44": "Hero Bow",
      "45": "Short Bow",
      "46": "Longbow",
      "47": "Miugre",
      "48": "Ballista",
      "49": "Iron Ballista",
      "50": "Killer Ballista",
      "51": "Fire",
      "52": "Thunder",
      "53": "Fimbulvetr",
      "54": "Elfire",
      "55": "Aircalibur",
      "56": "Fenrir",
      "57": "Bolting",
      "58": "Forblaze",
      "59": "Lightning",
      "60": "Divine",
      "61": "Purge",
      "62": "Aureola",
      "63": "Flux",
      "64": "Nosferatu",
      "65": "Eclipse",
      "66": "Apocalypse",
      "67": "Heal",
      "68": "Mend",
      "69": "Recover",
      "70": "Libro",
      "71": "Reserve",
      "72": "Warp",
      "73": "Rescue",
      "74": "Restore",
      "75": "Silence",
      "76": "Sleep",
      "77": "Torch",
      "78": "Hammerne",
      "79": "Watch",
      "80": "Berserk",
      "81": "Unlock",
      "82": "Shield",
      "83": "Fire Dragon Stone",
      "84": "Divine Dragon Stone",
      "85": "Magic Dragon Stone",
      "86": "Secret Book",
      "87": "Goddess Icon",
      "88": "Angelic Robe",
      "89": "Dragon Shield",
      "90": "Energy Ring",
      "91": "Speedwing",
      "92": "Talisman",
      "93": "Boots",
      "94": "Body Ring",
      "95": "Hero's Proof",
      "96": "Knight's Proof",
      "97": "Orion's Bolt",
      "98": "Elysian Whip",
      "99": "Guiding Ring",
      "100": "Chest Key (5)",
      "101": "Door Key",
      "102": "Bridge Key",
      "103": "Lockpick",
      "104": "Vulnerary",
      "105": "Elixir",
      "106": "Holy Water",
      "107": "Torch",
      "108": "Antitoxin",
      "109": "Member Card",
      "110": "Silver Card",
      "111": "Gold",
      "112": "Dark Breath",
      "113": "Exaccus",
      "114": "Steel Blade",
      "115": "Silver Blade",
      "116": "Al's Sword",
      "117": "Gant's Lance",
      "118": "Tina's Staff",
      "119": "Holy Maiden",
      "120": "Wyrmslayer",
      "121": "White Gem",
      "122": "Blue Gem",
      "123": "Red Gem",
      "124": "Delphi Shield",
      "125": "Runesword",
      "126": "Spear",
      "127": "Tomahawk"
    }
  },
  "FE7": {
    "character": {
      "0": "None",
      "1": "Eliwood",
      "2": "Hector",
      "3": "Lyn (Tutorial)",
      "4": "Raven",
      "5": "Geitz",
      "6": "Guy",
      "7": "Karel",
      "8": "Dorcas",
      "9": "Bartre",
      "10": "Citizen",
      "11": "Oswin",
      "12": "Fargus",
      "13": "Wil (Tutorial)",
      "14": "Rebecca",
      "15": "Louise",
      "16": "Lucius",
      "17": "Serra",
      "18": "Renault",
      "19": "Erk",
      "20": "Nino",
      "21": "Pent",
      "22": "Canas",
      "23": "Kent (Tutorial)",
      "24": "Sain (Tutorial)",
      "25": "Lowen",
      "26": "Marcus",
      "27": "Priscilla",
      "28": "Rath (Tutorial)",
      "29": "Florina (Tutorial)",
      "30": "Fiora",
      "31": "Farina",
      "32": "Heath",
      "33": "Vaida",
      "34": "Hawkeye",
      "35": "Matthew",
      "36": "Jaffar",
      "37": "Ninian",
      "38": "Nils",
      "39": "Athos",
      "40": "Merlinus",
      "41": "Nils(Final Chapter)",
      "42": "Uther",
      "43": "Vaida (Boss)",
      "44": "Wallace",
      "45": "Lyn (not tutorial)",
      "46": "Wil (not tutorial)",
      "47": "Kent (not tutorial)",
      "48": "Sain (not tutorial)",
      "49": "Florina (not tutorial)",
      "50": "Rath (not tutorial)",
      "51": "Dart",
      "52": "Isadora",
      "53": "Elenora",
      "54": "Legault",
      "55": "Karla",
      "56": "Harken",
      "57": "Leila",
      "58": "Bramimond",
      "59": "Kishuna",
      "60": "Groznyi",
      "61": "Wire",
      "62": "Bandit",
      "63": "Zagan",
      "64": "Boies",
      "65": "Puzon",
      "66": "Bandit",
      "67": "Santals",
      "68": "Nergal",
      "69": "Erik",
      "70": "Sealen",
      "71": "Bauker",
      "72": "Bernard",
      "73": "Damian",
      "74": "Zoldam",
      "75": "Uhai",
      "76": "Aion",
      "77": "Darin",
      "78": "Cameron",
      "79": "Oleg",
      "80": "Eubans",
      "81": "Ursula",
      "82": "Black Fang",
      "83": "Paul",
      "84": "Jasmine",
      "85": "Black Fang",
      "86": "Morph Jerme",
      "87": "Pascal",
      "88": "Kenneth",
      "89": "Jerme",
      "90": "Maxime",
      "91": "Sonia",
      "92": "Teodor",
      "93": "Georg",
      "94": "Kaim",
      "95": "Merc",
      "96": "Denning",
      "97": "Bern",
      "98": "Morph",
      "99": "Lloyd (Four-Fanged Offense)",
      "100": "Linus (Four-Fanged Offense)",
      "101": "Lloyd (Cog of Destiny)",
      "102": "Linus (Cog of Destiny)",
      "103": "Bandit",
      "104": "Bandit",
      "105": "Bandit",
      "106": "Laus",
      "107": "Laus",
      "108": "Pirate",
      "109": "Black Fang",
      "110": "Black Fang",
      "111": "Ostia",
      "112": "Black Fang",
      "113": "Guardian",
      "114": "Morph",
      "115": "Morph",
      "116": "Morph",
      "117": "Caelin",
      "118": "Caelin",
      "119": "Caelin",
      "120": "Laus",
      "121": "Laus",
      "122": "Zephiel",
      "123": "Elbert",
      "124": "Black Fang",
      "125": "Black Fang",
      "126": "Black Fang",
      "127": "Morph",
      "128": "Morph",
      "129": "Morph",
      "130": "Morph",
      "131": "Black Fang",
      "132": "Brendan",
      "133": "Limstella",
      "134": "Dragon",
      "135": "Batta",
      "136": "Bandit",
      "137": "Zugu",
      "138": "Bandit",
      "139": "Bandit",
      "140": "Bandit",
      "141": "Glass",
      "142": "Migal",
      "143": "Bandit",
      "144": "Bandit",
      "145": "Bandit",
      "146": "Bandit",
      "147": "Bandit",
      "148": "Carjiga",
      "149": "Bandit",
      "150": "Bandit",
      "151": "Bandit",
      "152": "Bandit",
      "153": "Bug",
      "154": "Bandit",
      "155": "Bandit",
      "156": "Bandit",
      "157": "Bandit",
      "158": "Natalie",
      "159": "Bool",
      "160": "Bandit",
      "161": "Bandit",
      "162": "Bandit",
      "163": "Bandit",
      "164": "Bandit",
      "165": "Bandit",
      "166": "Heintz",
      "167": "Black Fang",
      "168": "Black Fang",
      "169": "Black Fang",
      "170": "Black Fang",
      "171": "Black Fang",
      "172": "Black Fang",
      "173": "Beyard",
      "174": "Black Fang",
      "175": "Black Fang",
      "176": "Black Fang",
      "177": "Black Fang",
      "178": "Black Fang",
      "179": "Black Fang",
      "180": "Black Fang",
      "181": "Black Fang",
      "182": "Yogi",
      "183": "Caelin",
      "184": "Caelin",
      "185": "Caelin",
      "186": "Caelin",
      "187": "Caelin",
      "188": "Caelin",
      "189": "Caelin",
      "190": "Eagler",
      "191": "Caelin",
      "192": "Caelin",
      "193": "Caelin",
      "194": "Caelin",
      "195": "Caelin",
      "196": "Caelin",
      "197": "Lundgren",
      "198": "Caelin",
      "199": "Caelin",
      "200": "Caelin",
      "201": "Caelin",
      "202": "Caelin",
      "203": "Caelin",
      "204": "Caelin",
      "205": "Tactician",
      "206": "Citizen/SoldierG",
      "207": "Citizen/Soldier",
      "208": "Citizen",
      "209": "Citizen",
      "210": "Citizen",
      "211": "Citizen",
      "212": "Citizen",
      "213": "Citizen",
      "214": "Citizen",
      "215": "Merc",
      "216": "Pirate",
      "217": "Bandit",
      "218": "Citizen",
      "219": "Citizen",
      "220": "Citizen",
      "221": "Black Fang",
      "222": "Black Fang",
      "223": "Bandit",
      "224": "Black Fang",
      "225": "Morph",
      "226": "Black Fang",
      "227": "Black Fang",
      "228": "Bandit",
      "229": "Ostia",
      "230": "Rath's unit",
      "231": "Bandit",
      "232": "Bandit",
      "233": "Bern",
      "234": "Guardian",
      "235": "Morph",
      "236": "Laus",
      "237": "Bandit",
      "238": "Bandit",
      "239": "Bern",
      "240": "Guardian",
      "241": "Morph",
      "242": "Guardian",
      "243": "Black Fang",
      "244": "Morph Lloyd",
      "245": "Morph Linus",
      "246": "Morph Brendan",
      "247": "Morph Uhai",
      "248": "Morph Ursula",
      "249": "Morph Kenneth",
      "250": "Morph Darin",
      "251": "Enemy",
      "252": "Wall",
      "253": "Snag",
      "254": "None",
      "255": "None"
    },
    "class": {
      "0": "None",
      "1": "Eliwood Lord",
      "2": "Lyn Lord",
      "3": "Hector Lord",
      "4": "Eliwood Lord Knight (only by class name)",
      "5": "Lyn Blade Lord (only by class name)",
      "6": "Hector Great Lord (only by class name)",
      "7": "Eliwood Lord Knight",
      "8": "Lyn Blade Lord",
      "9": "Hector Great Lord",
      "10": "Mercenary",
      "11": "Mercenary",
      "12": "Hero",
      "13": "Hero",
      "14": "Myrmidon",
      "15": "Myrmidon",
      "16": "Swordmaster",
      "17": "Swordmaster",
      "18": "Fighter",
      "19": "Warrior",
      "20": "Knight",
      "21": "Knight",
      "22": "General",
      "23": "General",
      "24": "Archer",
      "25": "Archer",
      "26": "Sniper",
      "27": "Sniper",
      "28": "Monk",
      "29": "Cleric",
      "30": "Bishop",
      "31": "Bishop",
      "32": "Mage",
      "33": "Mage",
      "34": "Sage",
      "35": "Sage",
      "36": "Shaman",
      "37": "Shaman",
      "38": "Druid",
      "39": "Druid",
      "40": "Cavalier",
      "41": "Cavalier",
      "42": "Paladin",
      "43": "Paladin",
      "44": "Troubadour",
      "45": "Valkyrie",
      "46": "Nomad",
      "47": "Nomad",
      "48": "Nomad Trooper",
      "49": "Nomad Trooper",
      "50": "Pegasus Knight",
      "51": "Falcon Knight",
      "52": "Wyvern Knight",
      "53": "Wyvern Knight",
      "54": "Wyvern Lord",
      "55": "Wyvern Lord",
      "56": "Soldier",
      "57": "Brigand",
      "58": "Pirate",
      "59": "Berserker",
      "60": "Thief",
      "61": "Thief",
      "62": "Assassin",
      "63": "Civilian",
      "64": "Dancer",
      "65": "Bard",
      "66": "Archsage",
      "67": "Magic Seal",
      "68": "Transporter",
      "69": "Transporter",
      "70": "Fire Dragon",
      "71": "Civilian",
      "72": "Civilian (F)",
      "73": "Child",
      "74": "Brammimond",
      "75": "Peer",
      "76": "Peer (F)",
      "77": "Prince",
      "78": "Queen",
      "79": "Hung Leila",
      "80": "Corsair",
      "81": "Prince (Tactician)",
      "82": "Fallen Prince",
      "83": "Prince facing upward",
      "84": "Fallen Ninian",
      "85": "Fallen Ice Dragon",
      "86": "Fallen Warrior",
      "87": "Child",
      "88": "Child (F)",
      "89": "Transporter w/ Horse",
      "90": "Uber Sage",
      "91": "Archer in Ballista",
      "92": "Archer in Iron Ballista",
      "93": "Archer in Killer Ballista",
      "94": "Empty Ballista",
      "95": "Empty Iron Ballista",
      "96": "Empty Killer Ballista",
      "97": "Empty (Make a custom class!)",
      "98": "Empty (Make a custom class!)",
      "99": "Empty (Make a custom class!)"
    },
    "item": {
      "0": "None",
      "1": "Iron Sword",
      "2": "Slim Sword",
      "3": "Steel Sword",
      "4": "Silver Sword",
      "5": "Iron Blade",
      "6": "Steel Blade",
      "7": "Silver Blade",
      "8": "Poison Sword",
      "9": "Rapier",
      "10": "Mani Katti",
      "11": "Brave Sword",
      "12": "Wo Dao",
      "13": "Killing Edge",
      "14": "Armourslayer",
      "15": "Wyrmslayer",
      "16": "Light Brand",
      "17": "Rune Sword",
      "18": "Lancereaver",
      "19": "Long Sword",
      "20": "Iron Lance",
      "21": "Slim Lance",
      "22": "Steel Lance",
      "23": "Silver Lance",
      "24": "Poison Lance",
      "25": "Brave Spear",
      "26": "Killer Lance",
      "27": "Horseslayer",
      "28": "Javelin",
      "29": "Spear",
      "30": "Axereaver",
      "31": "Iron Axe",
      "32": "Steel Axe",
      "33": "Silver Axe",
      "34": "Poison Axe",
      "35": "Brave Axe",
      "36": "Killer Axe",
      "37": "Halberd",
      "38": "Hammer",
      "39": "Devil Axe",
      "40": "Hand Axe",
      "41": "Tomahawk",
      "42": "Swordreaver",
      "43": "Swordslayer",
      "44": "Iron Bow",
      "45": "Steel Bow",
      "46": "Silver Bow",
      "47": "Poison Bow",
      "48": "Killer Bow",
      "49": "Brave Bow",
      "50": "Short Bow",
      "51": "Longbow",
      "52": "Ballista",
      "53": "Iron Ballista",
      "54": "Killer Ballista",
      "55": "Fire",
      "56": "Thunder",
      "57": "Elfire",
      "58": "Bolting",
      "59": "Fimbulvetr",
      "60": "Forblaze",
      "61": "Excalibur",
      "62": "Lightning",
      "63": "Shine",
      "64": "Divine",
      "65": "Purge",
      "66": "Aura",
      "67": "Luce",
      "68": "Flux",
      "69": "Luna",
      "70": "Nosferatu",
      "71": "Eclipse",
      "72": "Fenrir",
      "73": "Gespenst",
      "74": "Heal",
      "75": "Mend",
      "76": "Recover",
      "77": "Physic",
      "78": "Fortify",
      "79": "Restore",
      "80": "Silence",
      "81": "Sleep",
      "82": "Berserk",
      "83": "Warp",
      "84": "Rescue",
      "85": "Torch",
      "86": "Hammerne",
      "87": "Unlock",
      "88": "Barrier",
      "89": "Dragon Axe",
      "90": "Angelic Robe",
      "91": "Energy Ring",
      "92": "Secret Book",
      "93": "Speedwings",
      "94": "Goddess Icon",
      "95": "Dragon Shield",
      "96": "Talisman",
      "97": "Boots",
      "98": "Body Ring",
      "99": "Hero's Crest",
      "100": "Knight's Crest",
      "101": "Orion's Bolt",
      "102": "Elysian Whip",
      "103": "Guiding Ring",
      "104": "Chest Key",
      "105": "Door Key",
      "106": "Lockpick",
      "107": "Vulnerary",
      "108": "Elixir",
      "109": "Pure Water",
      "110": "Antitoxin",
      "111": "Torch",
      "112": "Delphi Shield",
      "113": "Member Card",
      "114": "Silver Card",
      "115": "White Gem",
      "116": "Blue Gem",
      "117": "Red Gem",
      "118": "Gold",
      "119": "Uber Spear",
      "120": "Chest Key (5)",
      "121": "Mine",
      "122": "Light Rune",
      "123": "Iron Rune",
      "124": "Filla's Might",
      "125": "Ninis's Grace",
      "126": "Thor's Ire",
      "127": "Set's Litany",
      "128": "Emblem Sword",
      "129": "Emblem Spear",
      "130": "Emblem Axe",
      "131": "Emblem Bow",
      "132": "Durandal",
      "133": "Armads",
      "134": "Aureola",
      "135": "Earth Seal",
      "136": "Afa's Drops",
      "137": "Heaven Seal",
      "138": "Emblem Seal",
      "139": "Fell Contract",
      "140": "Sol Katti",
      "141": "Wolf Beil/Flamberge",
      "142": "Ereshkigal",
      "143": "Flametongue",
      "144": "Regal Blade",
      "145": "Rex Hasta",
      "146": "Basilikos",
      "147": "Rienfleche",
      "148": "Heavy Spear",
      "149": "Short Spear",
      "150": "Ocean Seal",
      "151": "3000 G",
      "152": "5000 G",
      "153": "Wind Sword",
      "154": "???"
    }
  },
  "FE8": {
    "character": {
      "0": "(No one/Not referenced)",
      "1": "Eirika",
      "2": "Seth",
      "3": "Gilliam",
      "4": "Frantz",
      "5": "Moulder",
      "6": "Vanessa",
      "7": "Ross",
      "8": "Neimi",
      "9": "Colm",
      "10": "Garcia",
      "11": "Innes",
      "12": "Lute",
      "13": "Natasha",
      "14": "Cougar",
      "15": "Ephraim",
      "16": "Forde",
      "17": "Kyle",
      "18": "Amelia",
      "19": "Artur",
      "20": "Gerik",
      "21": "Tethys",
      "22": "Marisa",
      "23": "Saleh",
      "24": "Ewan",
      "25": "L'Arachel",
      "26": "Dozla",
      "28": "Rennac",
      "29": "Duessel",
      "30": "Myrrh",
      "31": "Knoll",
      "32": "Joshua",
      "33": "Syrene",
      "34": "Tana",
      "35": "Lyon",
      "36": "Orson",
      "37": "Glen",
      "38": "Selena",
      "39": "Valter",
      "40": "Riev",
      "41": "Caellach",
      "42": "Fado",
      "43": "Ismaire",
      "44": "Hayden",
      "59": "Leon's Summon",
      "62": "Knoll's Summon",
      "63": "Yuan's Summon",
      "64": "Lyon (Ch 17)",
      "65": "Morva (Ch 20)",
      "66": "Orson (Ch 5x)",
      "67": "Valter (Ch 15)",
      "68": "Selena (Ch 10B & 13B)",
      "69": "Valter (Prologue)",
      "70": "Breguet (Ch 1)",
      "71": "Bone (Ch 2)",
      "72": "Bazba (Ch 3)",
      "73": "Mummy (Ch 4)",
      "74": "Saar (Ch 5)",
      "75": "Novala (Ch 6)",
      "76": "Murray (Ch 7)",
      "77": "Tirado (Ch 8)",
      "78": "Binks (Ch 9A)",
      "79": "Pablo (Ch 10A)",
      "80": "Macdaire (Ch 12A)",
      "81": "Aias (Ch 13A)",
      "82": "Carlyle (Ch 14A)",
      "83": "Caellach (Ch 15)",
      "84": "Pablo (Ch 13A)",
      "86": "Gorgon (Ch 18)",
      "87": "Riev (Ch 19 & 20)",
      "90": "Gheb (Ch 9B)",
      "91": "Beran (Ch 10B)",
      "92": "Cyclops (Ch 12B)",
      "93": "Hellbone (Ch 11A)",
      "94": "Death Gargoyle (Ch 11B)",
      "95": "Mummy",
      "102": "Mountain Thief",
      "104": "O'Neill (Prologue)",
      "105": "Glen (Cutscene)",
      "106": "Zonta (Ch 5x)",
      "107": "Vigarde (Ch 14B)",
      "108": "Lyon (Ch Final)",
      "109": "Orson (Ch 16)",
      "190": "Demon King",
      "192": "Frelian",
      "193": "Frelian",
      "197": "Fado (Renais)",
      "199": "Hayden (Frelia)",
      "200": "Mansel (Rausten)",
      "201": "Klimt (Carcino)",
      "202": "Dara (Caer Pelyn)",
      "203": "Ismaire (Jehanna)",
      "204": "Pegasus Messenger",
      "205": "Rausten Knight",
      "206": "Rausten Knight",
      "207": "(Untested starting and beyond this point)"
    },
    "class": {
      "0": "Separator/Nothing",
      "1": "Ephraim Lord",
      "2": "Eirika Lord",
      "3": "Ephraim Master Lord",
      "4": "Eirika Master Lord",
      "5": "Social Knight",
      "6": "Social Knight (F)",
      "7": "Paladin",
      "8": "Paladin (F)",
      "9": "Armour Knight",
      "10": "Armour Knight (F)",
      "11": "General",
      "12": "General (F)",
      "13": "Thief",
      "14": "Mamkute",
      "15": "Mercenary",
      "16": "Mercenary (F)",
      "17": "Hero",
      "18": "Hero (F)",
      "19": "Swordfighter",
      "20": "Swordfighter (F)",
      "21": "Swordmaster",
      "22": "Swordmaster (F)",
      "23": "Assassin",
      "24": "Assassin (F)",
      "25": "Archer",
      "26": "Archer (F)",
      "27": "Sniper",
      "28": "Sniper (F)",
      "29": "Forrest Knight",
      "30": "Forrest Knight (F)",
      "31": "Dragon Knight",
      "32": "Dragon Knight (F)",
      "33": "Dragon Master",
      "34": "Dragon Master (F)",
      "35": "Wyvern Knight",
      "36": "Wyvern Knight (F)",
      "37": "Mage",
      "38": "Mage (F)",
      "39": "Sage",
      "40": "Sage (F)",
      "41": "Mage Knight",
      "42": "Mage Knight (F)",
      "43": "Bishop",
      "44": "Bishop (F)",
      "45": "Shaman",
      "46": "Shaman (F)",
      "47": "Druid",
      "48": "Druid (F)",
      "49": "Summoner",
      "50": "Summoner (F)",
      "51": "Rogue",
      "52": "Gorgon Egg",
      "53": "Great Knight",
      "54": "Great Knight (F)",
      "55": "Trainee Soldier (2)",
      "56": "Trainee Fighter (3)",
      "57": "Trainee Mage (3)",
      "58": "Trainee Soldier (3)",
      "59": "Mamkute",
      "60": "Mamkute (F)",
      "61": "Trainee Fighter (1)",
      "62": "Trainee Mage (1)",
      "63": "Fighter",
      "64": "Warrior",
      "65": "Mountain Thief",
      "66": "Pirate",
      "67": "Berserker",
      "68": "Monk",
      "69": "Priest",
      "70": "Bard",
      "71": "Trainee Soldier (1)",
      "72": "Pegasus Knight",
      "73": "Falcon Knight",
      "74": "Sister",
      "75": "Troubadour",
      "76": "Valkyrie",
      "77": "Dancer",
      "78": "Soldier",
      "79": "Necromancer",
      "80": "Fleet",
      "81": "Ghost Fighter",
      "82": "Zombie",
      "83": "Mummy",
      "84": "Skeleton",
      "85": "Skeleton (Bow)",
      "86": "Hellbone",
      "87": "Hellbone (Bow)",
      "88": "Bael",
      "89": "Elder Bael",
      "90": "Cyclops",
      "91": "Mauthedoog",
      "92": "Cerberus",
      "93": "Tarvos",
      "94": "Macdaire",
      "95": "Bigl",
      "96": "Arch Bigl",
      "97": "Gorgon",
      "98": "Gorgon Egg",
      "99": "Gargoyle",
      "100": "Death Gargoyle",
      "101": "Dragon Zombie",
      "102": "Demon King",
      "103": "Archer on Ballista",
      "104": "Archer on Iron Ballista",
      "105": "Archer on Killer Ballista",
      "106": "Ballista",
      "107": "Iron Ballista",
      "108": "Killer Ballista",
      "109": "Civilian",
      "110": "Civilian (F)",
      "111": "Civilian",
      "112": "Civilian (F)",
      "113": "Civilian",
      "114": "Civilian (F)",
      "115": "Peer",
      "116": "Queen",
      "117": "Prince",
      "118": "Queen",
      "120": "Fallen Prince",
      "121": "Tent",
      "122": "Pontifex",
      "123": "Fallen Peer",
      "124": "Cyclops",
      "125": "Elder Bael",
      "126": "Trainee Fighter (2)",
      "127": "Trainee Mage (2)"
    },
    "item": {
      "0": "All Swords/   Separator",
      "1": "All Spears/   Iron Sword",
      "2": "All Axes/   Thin Sword",
      "3": "All Bows/   Steel Sword",
      "4": "All Staves/   Silver Sword",
      "5": "All Anima/   Iron Blade",
      "6": "All Light/   Steel Blade",
      "7": "All Dark/   Silver Blade",
      "8": "Poison Sword",
      "9": "Disarmed(required)/   Rapier",
      "10": "Mani Katti (DUMMY)",
      "11": "Hero Sword",
      "12": "Shamshir",
      "13": "Killer Sword",
      "14": "Armour Killer",
      "15": "Dragon Killer",
      "16": "Light Sword",
      "17": "Rune Sword",
      "18": "Lancebuster",
      "19": "Long Sword",
      "20": "Iron Spear",
      "21": "Thin Spear",
      "22": "Steel Spear",
      "23": "Silver Spear",
      "24": "Poison Spear",
      "25": "Hero Spear",
      "26": "Killer Spear",
      "27": "Horse Killer",
      "28": "Javelin",
      "29": "Slender Spear",
      "30": "Axebuster",
      "31": "Iron Axe",
      "32": "Steel Axe",
      "33": "Silver Axe",
      "34": "Poison Axe",
      "35": "Hero Axe",
      "36": "Killer Axe",
      "37": "Halberd",
      "38": "Hammer",
      "39": "Devil Axe",
      "40": "Hand Axe",
      "41": "Tomahawk",
      "42": "Swordbuster",
      "43": "Swordkiller",
      "44": "Trainee Axe",
      "45": "Iron Bow",
      "46": "Steel Bow",
      "47": "Silver Bow",
      "48": "Poison Bow",
      "49": "Killer Bow",
      "50": "Hero Bow",
      "51": "Short Bow",
      "52": "Long Bow",
      "53": "Iron Ballista",
      "54": "Killer Ballista",
      "55": "Ballista",
      "56": "Fire",
      "57": "Thunder",
      "58": "Elfire",
      "59": "Thunderstorm",
      "60": "Fimbulvetr",
      "61": "Forblaze (DUMMY)",
      "62": "Excalibur",
      "63": "Lightning",
      "64": "Shine",
      "65": "Divine",
      "66": "Purge",
      "67": "Aura",
      "68": "Luce (DUMMY)",
      "69": "Flux",
      "70": "Luna",
      "71": "Nosferatu",
      "72": "Eclipse",
      "73": "Fenrir",
      "74": "Gleipnir",
      "75": "Live",
      "76": "Relive",
      "77": "Recover",
      "78": "Libro",
      "79": "Reserve",
      "80": "Rest",
      "81": "Silence",
      "82": "Sleep",
      "83": "Berserk",
      "84": "Warp",
      "85": "Rescue",
      "86": "Torch",
      "87": "Hammerne",
      "88": "Unlock",
      "89": "Magic Shield",
      "90": "Dragon Axe",
      "91": "Angelic Robe",
      "92": "Energy Ring",
      "93": "Secret Book",
      "94": "Speedwings",
      "95": "Goddess Icon",
      "96": "Dragonshield",
      "97": "Talisman",
      "98": "Boots",
      "99": "Body Ring",
      "100": "Hero's Proof",
      "101": "Knight's Proof",
      "102": "Orion's Bolt",
      "103": "Elysian Whip",
      "104": "Guiding Ring",
      "105": "Chest Key",
      "106": "Door Key",
      "107": "Thief Key",
      "108": "Vulnerary",
      "109": "Elixir",
      "110": "Holy Water",
      "111": "Antidote",
      "112": "Torch",
      "113": "Free Shield",
      "114": "Member Card",
      "115": "Silver Card",
      "116": "White Gem",
      "117": "Blue Gem",
      "118": "Red Gem",
      "119": "1G",
      "120": "Reginleif",
      "121": "Chest Key (5)",
      "122": "Mine (DUMMY)",
      "123": "Light Rune (DUMMY)",
      "124": "Hopron Shield",
      "125": "Filla's Might (DUMMY)",
      "126": "Ninis's Grace (DUMMY)",
      "127": "Thor's Ire (DUMMY)",
      "128": "Set's Litany (DUMMY)",
      "129": "Shadow Killer",
      "130": "Bright Lance",
      "131": "Fiend Cleaver",
      "132": "Beacon Bow",
      "133": "Sieglind",
      "134": "Battle Axe",
      "135": "Ivaldi",
      "136": "Master Proof",
      "137": "Metis's Tome",
      "138": "Heaven Seal (DUMMY)",
      "139": "Sharp Claw",
      "140": "Latona",
      "141": "Dragon Spear",
      "142": "Vidofnir",
      "143": "Naglfal",
      "144": "Decaying Breath",
      "145": "Audomra",
      "146": "Siegmund",
      "147": "Garm",
      "148": "Nidhogg",
      "149": "Heavy Spear",
      "150": "Short Spear",
      "151": "Conqueror's Proof",
      "152": "Moon Bracelet",
      "153": "Sun Bracelet",
      "154": "1G",
      "155": "5G",
      "156": "10G",
      "157": "50G",
      "158": "100G",
      "159": "3000G",
      "160": "5000G",
      "161": "Wind Sword",
      "162": "Vulnerary",
      "163": "Vulnerary (green note)",
      "164": "Vulnerary (red note)",
      "165": "Dance",
      "166": "Nightmare",
      "167": "Demon Shard",
      "168": "Demon Light",
      "169": "Ravager",
      "170": "Holy Dragon Stone",
      "171": "Demon Surge",
      "172": "Shadowshot",
      "173": "Rotten Claw",
      "174": "Fetid Claw",
      "175": "Poison Claw",
      "176": "Long Poison Claw",
      "177": "Fire Fang",
      "178": "Hell Fang",
      "179": "Evil Eye",
      "180": "Bloody Eye",
      "181": "Stone",
      "182": "Aircalibur",
      "183": "Juna Fruit",
      "184": "150G",
      "185": "200G",
      "186": "Black Gem",
      "187": "Gold Gem"
    }
  }
}

function normalizeLookupName(kind: IdLookupKind, name: string): string {
  if (kind !== 'item') {
    return name.trim()
  }

  const slashIndex = name.lastIndexOf('/')
  const normalized = slashIndex >= 0 ? name.slice(slashIndex + 1) : name
  return normalized.trim()
}

export function resolveIdDisplayName(
  gameCode: GameCode,
  kind: IdLookupKind,
  id: number,
): string | null {
  if (!Number.isSafeInteger(id) || id < 0) return null
  const gameLookup = ID_LOOKUPS[gameCode]
  if (!gameLookup) return null
  const rawName = gameLookup[kind][id]
  if (!rawName) return null
  return normalizeLookupName(kind, rawName)
}
